export const THEMES = {
  dark: {
    name: 'Dark',
    backgroundColor: '#262f39',
    textColor: '#FFFFFF',
    subtextColor: '#CCCCCC',
    isGradient: false,
    inputBg: 'rgba(255, 255, 255, 0.1)',
    inputBorder: 'rgba(255, 255, 255, 0.3)',
    inputText: '#FFFFFF',
    inputPlaceholder: 'rgba(255, 255, 255, 0.6)',
  },
  offWhite: {
    name: 'Off-white',
    backgroundColor: '#FAFAF8',
    textColor: '#8B4513',
    subtextColor: '#666666',
    isGradient: false,
    inputBg: '#FFFFFF',
    inputBorder: '#E0E0E0',
    inputText: '#1A1A1A',
    inputPlaceholder: '#999',
  },
  cream: {
    name: 'Cream',
    backgroundColor: '#F5F5DC',
    textColor: '#654321',
    subtextColor: '#666666',
    isGradient: false,
    inputBg: '#FFFFFF',
    inputBorder: '#D2B48C',
    inputText: '#1A1A1A',
    inputPlaceholder: '#999',
  },
  wheat: {
    name: 'Wheat',
    backgroundColor: '#FFF8E7',
    textColor: '#8B4513',
    subtextColor: '#666666',
    isGradient: false,
    inputBg: '#FFFFFF',
    inputBorder: '#E8A540',
    inputText: '#1A1A1A',
    inputPlaceholder: '#999',
  },
  gradient: {
    name: 'Gradient',
    backgroundColor: 'gradient',
    textColor: '#654321',
    subtextColor: '#666666',
    isGradient: true,
    gradientColors: ['#F5F5DC', '#FFF8E7', '#E8A540'],
    inputBg: 'rgba(255, 255, 255, 0.85)',
    inputBorder: '#D4922A',
    inputText: '#1A1A1A',
    inputPlaceholder: '#999',
  },
};

export const ACTIVE_THEME = THEMES.wheat;